variables:
  - &node_image "node:14-alpine"
  - &buildx_image "woodpeckerci/plugin-docker-buildx"
  - &platforms "linux/amd64,linux/arm64,linux/arm/v7"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

pipeline:
  - name: Install Dependencies
    image: *node_image
    commands:
      - npm install

  - name: Generate version file
    image: alpine/git
    commands:
      - git describe --always --tags > version

  - name: Lint
    image: *node_image
    commands:
      - npm run lint

  - name: Test
    image: *node_image
    environment:
      DB_HOST: mongodb
      DB_PORT: "27017"
      DB_DATABASE: test-yasifys-tools
      DB_USERNAME: admin
      DB_PASSWORD: password
    commands:
      - npm test --coverage

  - name: SonarQube Scan
    image: sonarsource/sonar-scanner-cli:4.8.0
    secrets: [sonar_token]
    environment:
      SONAR_HOST_URL: "https://sonar.vahngomes.dev"
    commands:
      - sonar-scanner

  - name: Deploy to Docker Hub
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: latest
    when:
      event: push

  - name: Deploy Tagged Version
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: [latest, "${CI_COMMIT_TAG#v}"]
    when:
      event: tag

  - name: Deploy Pull Request
    image: *buildx_image
    secrets: [docker_username, docker_password]
    settings:
      repo: insidiousfiddler/yasifystools
      dockerfile: Dockerfile
      platforms: *platforms
      tag: pull_${CI_COMMIT_PULL_REQUEST}
    when:
      event: pull_request

branches: [main]
ignore_paths: [README.md, LICENSE, .github, .gitignore]
